# Run local development environment for Remote Camera Streaming Platform
$ErrorActionPreference = "Stop"

Write-Host "=========================================================="
Write-Host "Remote Camera Streaming Platform - Local Development Setup"
Write-Host "=========================================================="
Write-Host ""
Write-Host "1. MediaMTX Streaming Server:"
Write-Host "   mediamtx streaming/mediamtx/mediamtx.yml"
Write-Host ""
Write-Host "2. Backend API (FastAPI + Uvicorn):"
Write-Host "   uvicorn backend.app.main:app --reload --host 127.0.0.1 --port 8000"
Write-Host ""
Write-Host "3. Frontend Dashboard (React + Vite):"
Write-Host "   cd frontend && npm run dev"
Write-Host ""
Write-Host "Access Points:"
Write-Host "  - Frontend: http://localhost:5173"
Write-Host "  - Backend API: http://127.0.0.1:8000"
Write-Host "  - Health Check: http://127.0.0.1:8000/healthz"
